version: 2.1

jobs:
  build-docker:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t my-app:test .
      - run:
          name: Save Docker Image
          command: docker save -o my-app.tar my-app:test
      - persist_to_workspace:
          root: .
          paths:
            - my-app.tar

  run-cypress:
    machine: true  # Use full VM with Docker pre-installed
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load Docker Image
          command: docker load -i my-app.tar
      - run:
          name: Start Docker Container
          command: docker run -d -p 3000:3000 --name my-app-container my-app:test
      - run:
          name: Install Cypress
          command: npm install -g cypress
      - run:
          name: Run Cypress Tests
          command: npx cypress run --config baseUrl=http://localhost:3000
      - run:
          name: Stop and Remove Container
          command: |
            docker stop my-app-container
            docker rm my-app-container

workflows:
  version: 2
  test:
    jobs:
      - build-docker
      - run-cypress:
          requires:
            - build-docker
