version: 2.1

jobs:
  build-docker:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t my-app:test .
      - run:
          name: Save Docker Image
          command: docker save -o my-app.tar my-app:test
      - persist_to_workspace:
          root: .
          paths:
            - my-app.tar
            - cypress.config.js  # Ensure Cypress config is available
            - cypress/  # Persist the Cypress folder

  run-cypress:
    machine: true  # Use full VM with Docker & npm pre-installed
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Verify Workspace Files
          command: ls -la  # Debugging step to check files
      - run:
          name: Load Docker Image
          command: docker load -i my-app.tar
      - run:
          name: Start Docker Container
          command: docker run -d -p 3000:3000 --name my-app-container my-app:test
      - run:
          name: Ensure Cypress Config Exists
          command: | # This should be a file in support folder inside cypress
            if [ ! -f cypress.config.js ]; then
              echo "module.exports = { e2e: { baseUrl: 'http://localhost:3000' } };" > cypress.config.js
            fi
      - run:
          name: Ensure Cypress Support File Exists
          command: |
            mkdir -p cypress/support
            echo "// Cypress support file" > cypress/support/e2e.js
      - run:
          name: Install Cypress
          command: npm install -g cypress
      - run:
          name: Run Cypress Tests
          command: npx cypress run
      - run:
          name: Stop and Remove Container
          command: |
            docker stop my-app-container
            docker rm my-app-container

workflows:
  version: 2
  test:
    jobs:
      - build-docker
      - run-cypress:
          requires:
            - build-docker
